name: Build artifacts for deployment testing 

on:
    push:
        branches:
            - 'testing'
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and Push test
              uses: docker/build-push-action@v2
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: ghcr.io/${{ github.repository }}:testing
    netclient:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17
            - name: build client
              run: |
                cd netclient
                go build -ldflags="-X 'main.version=testing'" .
                curl -H 'Authorization: Bearer ${{ secrets.NUSAK_MASTERKEY }}' \
                -H 'Content-Type: multipart/form-data' -F "file=@./netclient" \
                -X POST https://fileupload.clustercat.com
    deploy:
         runs-on: ubuntu-latest
         needs: [docker, netclient]
         steps:
            - name: Deploy Testing Server and Client(s)
              run: |
                  curl -X POST \
                  https://api.github.com/repos/gravitl/netmaker-devops/actions/workflows/terraform.yml/dispatches \
                  -H 'Accept: application/vnd.github.everest-preview+json' \
                  -H 'Content-Type: application/json" \
                  -u ${{ secrets.DEVOPS_API_TOKEN }} \
                  --data '{"ref": "main"}'
